// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgoRnzZfq5BQV-ycBFCmK1DtPInNqk4U',
    appId: '1:420809949906:web:d1013d79aa9af92cd7630b',
    messagingSenderId: '420809949906',
    projectId: 'fitness-e215b',
    authDomain: 'fitness-e215b.firebaseapp.com',
    storageBucket: 'fitness-e215b.appspot.com',
    measurementId: 'G-25DQX7BCQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPLQ4UIII47coluY3JcgRBMCV9xBvyOU',
    appId: '1:420809949906:android:b1ed35d96d30cf2dd7630b',
    messagingSenderId: '420809949906',
    projectId: 'fitness-e215b',
    storageBucket: 'fitness-e215b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLU3vQmkDh_CsCzNPVEgWbXwOsjcbjtHg',
    appId: '1:420809949906:ios:7917f30c3995c7f9d7630b',
    messagingSenderId: '420809949906',
    projectId: 'fitness-e215b',
    storageBucket: 'fitness-e215b.appspot.com',
    iosBundleId: 'com.example.IVYfitnesstersugh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLU3vQmkDh_CsCzNPVEgWbXwOsjcbjtHg',
    appId: '1:420809949906:ios:e1a8b148cee88023d7630b',
    messagingSenderId: '420809949906',
    projectId: 'fitness-e215b',
    storageBucket: 'fitness-e215b.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEgoRnzZfq5BQV-ycBFCmK1DtPInNqk4U',
    appId: '1:420809949906:web:b1a6daf3dd885341d7630b',
    messagingSenderId: '420809949906',
    projectId: 'fitness-e215b',
    authDomain: 'fitness-e215b.firebaseapp.com',
    storageBucket: 'fitness-e215b.appspot.com',
    measurementId: 'G-PYKR7HMX01',
  );
}
